/*
 * SSD_Program.c
 *
 *  Created on: Mar 31, 2023
 *      Author: DWEEBSTARK
 */
#include "../../MCAL/DIO/DIO_Interface.h"
#include <util/delay.h>

#include "SSD_Private.h"
#include "SSD_Config.h"

#include "SSD_Interface.h"




void SSD_VoidInit(void){
	//Setting all Pins including COMMON PIN TO OUTPUT
	DIO_s8SetPortDirection(SSD_PORT,DIO_U8_PORT_DIR_OUTPUT);
//	//Setting All Pins to OFF
#if	(SSD_CONNECTION==SSD_COMMON_ANODE)
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_HIGH);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_HIGH);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_HIGH);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_HIGH);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_HIGH);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_HIGH);
//	DIO_u8SetPortValue(SSD_PORT,DI0_U8_PORT_HIGH);
//	//Setting All Pins to OFF
#elif (SSD_CONNECTION==SSD_COMMON_CATHODE)
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_LOW);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
	DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);
#endif
}

void SSD_VoidTurnOn(void){
	//Sending Signal to turn on SSD to common Pin
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
	DIO_s8SetPinValue(SSD_PORT,SSD_COMMON_PIN,DIO_U8_PIN_HIGH);

#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
	DIO_s8SetPinValue(SSD_PORT,SSD_COMMON_PIN,DIO_U8_PIN_LOW);

#endif
}

void SSD_VoidTurnOff(void){
	//Sending Signal to turn off SSD to common Pin
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
	DIO_s8SetPinValue(SSD_PORT,SSD_COMMON_PIN,DIO_U8_PIN_LOW);

#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
	DIO_s8SetPinValue(SSD_PORT,SSD_COMMON_PIN,DIO_U8_PIN_HIGH);

#endif
}
void SSD_VoidDisplayNumber(s8 Number){

	switch(Number){

	case 0:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
//		PORTB&=128;
//		PORTB|=SSD_DisplayZERO;
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_HIGH);
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayZERO);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayZERO);
#endif
		break;
	case 1:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_HIGH);
//		PORTB&=128;
//		PORTB|=SSD_DisplayONE;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayONE);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayONE);
#endif
		break;

	case 2:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);
//		PORTB&=128;
//		PORTB|=SSD_DisplayTWO;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayTWO);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayTWO);
#endif
		break;
	case 3:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);
//		PORTB&=128;
//		PORTB|=SSD_DisplayTHREE;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayTHREE);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayTHREE);
#endif
		break;

	case 4:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);

//		PORTB&=128;
//		PORTB|=SSD_DisplayFOUR;
////		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayFOUR);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayFOUR);
#endif
		break;

	case 5:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);

		//		PORTB&=128;
//		PORTB|=SSD_DisplayFIVE;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayFIVE);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayFIVE);
#endif
		break;

	case 6:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);
		//		PORTB&=128;
//		PORTB|=SSD_DisplaySIX;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplaySIX);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplaySIX);
#endif
		break;

	case 7:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_HIGH);
//		PORTB&=128;
//		PORTB|=SSD_DisplaySEVEN;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplaySEVEN);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplaySEVEN);
#endif
		break;

	case 8:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);
//		PORTB&=128;
//		PORTB|=SSD_DisplayEIGHT;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayEIGHT);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayEIGHT);
#endif
		break;
	case 9:
#if	SSD_CONNECTION==(SSD_COMMON_ANODE)
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_A,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_B,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_C,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_D,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_E,DIO_U8_PIN_HIGH);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_F,DIO_U8_PIN_LOW);
		DIO_s8SetPinValue(SSD_PORT,SSD_BAR_G,DIO_U8_PIN_LOW);
//		PORTB&=128;
//		PORTB|=SSD_DisplayNINE;
//		DIO_u8SetPortValue(SSD_PORT,SSD_DisplayNINE);
#elif SSD_CONNECTION==(SSD_COMMON_CATHODE)
		DIO_u8SetPortValue(SSD_PORT,~SSD_DisplayNINE);
#endif
		break;
	default:
		break;
	}

}
